#VARS::
substitutions:
  time_sntp_id: sntp_time
  time_sntp_tz: Europe/Berlin
  time_sntp_srv1: ptbtime1.ptb.de
  time_sntp_srv2: ntp1.ewetel.de
  time_sntp_srv3: de.pool.ntp.org
  
# Example configuration entry
time:
  - platform: sntp
    id: ${time_sntp_id}
    timezone: ${time_sntp_tz}
    servers:
     - ${time_sntp_srv1}
     - ${time_sntp_srv3}
     - ${time_sntp_srv3}
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock by SNTP source"

#text_sensor:
#  - platform: template
#    name: "Current time"
#    lambda: |-
#      char str[30]; 
#      time_t currTime = id(${time_sntp_id}).now().timestamp;
#      strftime(str, sizeof(str), "%H:%M", localtime(&currTime));
#      return  { str };
#    update_interval: 10s