##
# vars:
#
#   wlan_ssid_ap
#   wlan_pass_ap

# Over-the-Air connection
ota:
  - platform: !secret "ota_platform"
    id: !secret "ota_id"
    password: !secret "ota_pass"

# Default wifi connection
wifi:
  ssid: !secret "wifi_ssid"
  password: !secret "wifi_pass"

<<<<<<< HEAD
=======
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${wifi_ssid_ap}
    password: ${wifi_pass_ap}

captive_portal:

>>>>>>> 287af9c63fdaa2e73654d8d97df95479e1d5bd33
# Send wifi feedback
text_sensor:
  - platform: "wifi_info"
    ip_address:
      name: "ESP Wifi IP Address"
    ssid:
      name: "ESP Wifi Connected SSID"
    mac_address:
      name: "ESP Wifi Mac Address"
